{% set name = "KegAlign" %}
{% set version = "0.1.2.7" %}
{% set kegalign_python_version = "3.12.*" %}
{% set kegalign_tbb_version = "2020.2.*" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/galaxyproject/KegAlign/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 79706f8edee458570af61dcf667317f66d4cb0b04f84c8591da9b57d5ddf1ae6


build:
  number: 0
  skip: true  # [win or osx or cuda_compiler_version is undefined or cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - make
  host:
    {% if cuda_compiler_version is not undefined %}
    - cuda-version {{ cuda_compiler_version }}
    {% endif %}
    - libboost-devel
    - tbb-devel {{ kegalign_tbb_version }}
    - zlib
  run:
    - {{ pin_compatible("cuda-version", min_pin="x.x", max_pin="x") }}
    - bash
    - bashlex
    - coreutils
    - gawk
    - grep
    - nvidia-ml-py
    - python {{ kegalign_python_version }}
    - sed
    - tbb-devel {{ kegalign_tbb_version }}
    - time

test:
  commands:
    - kegalign --help

about:
  home: https://github.com/galaxyproject/KegAlign
  summary: 'KegAlign: A Scalable GPU-Based Whole Genome Aligner'
  description: |
    KegAlign is a Scalable GPU System for Pairwise Whole Genome
    Alignments based on LASTZ's seed-filter-extend paradigm.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/galaxyproject/KegAlign/blob/main/README.md
  dev_url: https://github.com/galaxyproject/KegAlign

extra:
  recipe-maintainers:
    - richard-burhans
